/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author ASUS
 */
public class Register extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Register.class.getName());

    /**
     * Creates new form Login
     */
    public Register() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLblUserName = new javax.swing.JLabel();
        jLblPassword = new javax.swing.JLabel();
        jTxtRegisterUserName = new javax.swing.JTextField();
        jBtnRegisterPassword = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jBtnRegister = new javax.swing.JButton();
        jLblPassword1 = new javax.swing.JLabel();
        jBtnRegisterReEnterPassword = new javax.swing.JPasswordField();
        jBtnSignIn = new javax.swing.JButton();
        jLblUserName1 = new javax.swing.JLabel();
        jTxtUserRegisterToken = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1085, 730));

        jLabel1.setFont(new java.awt.Font("Eras Bold ITC", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sunrise Dental Clinic");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 102));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("First Log In");

        jLblUserName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLblUserName.setForeground(new java.awt.Color(51, 51, 51));
        jLblUserName.setText("User Name ");

        jLblPassword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLblPassword.setForeground(new java.awt.Color(51, 51, 51));
        jLblPassword.setText("Password");

        jTxtRegisterUserName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTxtRegisterUserName.setToolTipText("");
        jTxtRegisterUserName.setName(""); // NOI18N
        jTxtRegisterUserName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxtRegisterUserNameKeyReleased(evt);
            }
        });

        jBtnRegisterPassword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jBtnRegisterPassword.addActionListener(this::jBtnRegisterPasswordActionPerformed);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/src/converted_image.png"))); // NOI18N

        jBtnRegister.setBackground(new java.awt.Color(0, 102, 255));
        jBtnRegister.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBtnRegister.setForeground(new java.awt.Color(255, 255, 255));
        jBtnRegister.setText("Register");
        jBtnRegister.addActionListener(this::jBtnRegisterActionPerformed);

        jLblPassword1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLblPassword1.setForeground(new java.awt.Color(51, 51, 51));
        jLblPassword1.setText("Re Enter Password");

        jBtnRegisterReEnterPassword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jBtnRegisterReEnterPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jBtnRegisterReEnterPasswordKeyReleased(evt);
            }
        });

        jBtnSignIn.setBackground(new java.awt.Color(0, 102, 255));
        jBtnSignIn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBtnSignIn.setForeground(new java.awt.Color(255, 255, 255));
        jBtnSignIn.setText("Sign In");
        jBtnSignIn.addActionListener(this::jBtnSignInActionPerformed);

        jLblUserName1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLblUserName1.setForeground(new java.awt.Color(51, 51, 51));
        jLblUserName1.setText("Token");

        jTxtUserRegisterToken.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTxtUserRegisterToken.setToolTipText("");
        jTxtUserRegisterToken.setName(""); // NOI18N
        jTxtUserRegisterToken.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxtUserRegisterTokenKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblUserName)
                    .addComponent(jLblPassword)
                    .addComponent(jLblPassword1)
                    .addComponent(jLblUserName1))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTxtRegisterUserName)
                    .addComponent(jBtnRegisterPassword)
                    .addComponent(jBtnRegisterReEnterPassword)
                    .addComponent(jBtnRegister)
                    .addComponent(jTxtUserRegisterToken, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(99, 99, 99)
                .addComponent(jLabel4)
                .addGap(82, 82, 82)
                .addComponent(jLabel3)
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(331, 331, 331)
                .addComponent(jBtnSignIn)
                .addGap(60, 60, 60))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jBtnSignIn))
                .addGap(115, 115, 115)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLblUserName1)
                            .addComponent(jTxtUserRegisterToken, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLblUserName)
                            .addComponent(jTxtRegisterUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtnRegisterPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLblPassword))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLblPassword1)
                            .addComponent(jBtnRegisterReEnterPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(jBtnRegister))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jTxtRegisterUserName.getAccessibleContext().setAccessibleName("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnRegisterPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRegisterPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnRegisterPasswordActionPerformed

    private void jBtnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRegisterActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jBtnRegisterActionPerformed

    private void jBtnSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSignInActionPerformed
        // TODO add your handling code here
        Login form = new Login();
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBtnSignInActionPerformed

    private void jBtnRegisterReEnterPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBtnRegisterReEnterPasswordKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnRegisterReEnterPasswordKeyReleased

    private void jTxtRegisterUserNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtRegisterUserNameKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtRegisterUserNameKeyReleased

    private void jTxtUserRegisterTokenKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtUserRegisterTokenKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtUserRegisterTokenKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Register().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnRegister;
    private javax.swing.JPasswordField jBtnRegisterPassword;
    private javax.swing.JPasswordField jBtnRegisterReEnterPassword;
    private javax.swing.JButton jBtnSignIn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLblPassword;
    private javax.swing.JLabel jLblPassword1;
    private javax.swing.JLabel jLblUserName;
    private javax.swing.JLabel jLblUserName1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTxtRegisterUserName;
    private javax.swing.JTextField jTxtUserRegisterToken;
    // End of variables declaration//GEN-END:variables
}
